#pragma once

//basic


#define SSD_DEVICE_ADDRESS 0x3C
#define SSD_I2C_FREQ (400 * 1000)
#define SSD_CTRL_CMD 0b00000000
#define SSD_CTRL_DAT 0b01000000

//hardware control
#define SSD_COMMAND_SETCONTRAST 0x81
#define SSD_COMMAND_ON 0xA4
#define SSD_COMMAND_FULL_ON 0xA5
#define SSD_COMMAND_SET_NORMAL 0xA6
#define SSD_COMMAND_SET_INVERSE 0xA7
#define SSD_COMMAND_SET_MUX_RATIO 0xA8
#define SSD_COMMAND_SET_OFFSET 0xD3
#define SSD_COMMAND_POWER_ON 0xAF
#define SSD_COMMAND_POWER_OFF 0xAE
#define SSD_COMMAND_SET_START_LINE 0x50
#define SSD_COMMAND_SET_COM_CONFIG 0xDA



//scrolling
#define SSD_COMMAND_RIGHT_HOR_SCROLL 0x26
#define SSD_COMMAND_LEFT_HOR_SCROLL 0x27

//addressing mode
#define SSD_COMMAND_ADR_MODE 0x20
#define SSD_ADR_MODE_HOR 0b00000000
#define SSD_ADR_MODE_VER 0b00000001
#define SSD_ADR_MODE_PAG 0b00000010

#define SSD_COMMAND_SET_COL_ADR 0x21
#define SSD_COMMAND_SET_PAGE_ADR 0x22

#define SSD_COMMAND_SET_CLK_DIV 0xD5
#define SSD_COMMAND_SET_PRECHARGE 0xD9
#define SSD_COMMAND_SET_VCOMH 0xDB

//invert mapping
#define SSD_COMMAND_SEG_INVERT_OFF 0xA0
#define SSD_COMMAND_SEG_INVERT_ON 0xA1
#define SSD_COMMAND_COM_INVERT_OFF 0xC0
#define SSD_COMMAND_COM_INVERT_ON 0xC8


#define SSD_HEIGHT 64
#define SSD_WIDTH 128
#define SSD_FRAME_SIZE ((SSD_HEIGHT * SSD_WIDTH) / 8)


void ssd_clear();

void ssd_init();

void ssd_print();